### ISSUE TITLE
Helping out with pixel data decoding

### ISSUE THREAD

**Issue by pevers** [Enet4/dicom-rs#111]
Hi @Enet4 !

Thanks for this awesome library! 

I'm now using this library to generate thumbnails for a bunch of JPEG lossless compressed dicoms that I have. I created a simple abstraction here: https://github.com/pevers/dicom-pixel-data, using GDCM bindings to decode pixel data into a `DynamicImage`:

Example from the tests:
```rust
let obj = open_file(dicom_test_files::path(value).unwrap()).unwrap();
let image = obj.decode_pixel_data().unwrap().to_dynamic_image().unwrap();
image
    .save(format!(
        "out.png",
    ))
    .unwrap();
```

Not everything is supported yet, but it can at least decode a bunch of example lossless JPEG dicoms from the Pydicom test set. I created a thin GDCM wrapper because I don't think there is solid support for the wide variety of dicom compression formats in Rust.

**My question:** I read on roadmap that this is a requested feature. Can I help by creating a PR to this repo? Or is this already in the making? I'm fairly new to Rust so I guess it would require some extensive reviewing but I would be glad to help out a bit.

Thanks again for your work!

Cheers

**Comment by Enet4** [comment]
Hello! 👋It's great to know DICOM-rs is presenting itself useful to you!

Yes, it is in the project's plans to provide a uniform way to decode images out of DICOM objects, and I am thrilled to already see more efforts towards this functionality!

The project has so far favoured the use of implementations in pure Rust, but I suppose that the GDCM wrapper could provide a way to bootstrap pixel data decoding, and pure implementations could be added over time in future iterations. The only thing that could become a challenge is the integration with the transfer syntax concept at `dicom-encoding`, but this one will likely need to be modified to make way for this feature anyway. (Any questions about this in particular, feel free to ask.)

If you are willing to send in a PR, I would be glad to review it on the various aspects, including on writing idiomatic Rust. I also have a few notes about a vision for the image abstraction API that I could share.

**Comment by Enet4** [comment]
Thank you! Now with #112 merged, we can keep track of further developments at #125.
