### ISSUE TITLE
[pixeldata] Enable building without GDCM

### ISSUE THREAD

**Issue by Enet4** [Enet4/dicom-rs#121]
Even if at the cost of supporting less encodings, there should be a way to make this abstraction work without GDCM. Support for WebAssembly comes to mind, which becomes more complicated when linking to other native libraries is involved.
Putting gdcm behind a Cargo feature enabled by default seems ideal for now.

**Comment by pevers** [comment]
I'll try to take a stab at this because I would really like to compile dicom-rs as WASM.

**Comment by Enet4** [comment]
Covered by #131. :+1:
