### ISSUE TITLE
Account for Planar Configuration

### ISSUE THREAD

**Issue by Enet4** [Enet4/dicom-rs#129]
This was previously overlooked, but the Planar Configuration (0028,0006) attribute should be checked whenever the image has more than one sample per pixel. At the moment, the decoding functions assume that it is in standard order (`0`), and may have funny results if it is in channel-first order (`1`).

Relevant part of the standard: [Part 3, section C.7.6.3](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.3.html#sect_C.7.6.3.1.3)

**Comment by abustany** [comment]
related PR: https://github.com/Enet4/dicom-rs/pull/575
