### ISSUE TITLE
parse_date Error

### ISSUE THREAD

**Issue by jmlaka** [Enet4/dicom-rs#136]
Hello, thank you for your wonderfull work as I can use your library and learn Rust from your code.
I found a little bug 

in
core::value::deserialize.rs

line 53
                NaiveDate::from_ymd_opt(year, month as u32, 0).context(InvalidDateTimeZone);
change to 
                NaiveDate::from_ymd_opt(year, month as u32, 1).context(InvalidDateTimeZone);

add test:
        assert_eq!(
        parse_date(b"197112").unwrap(),
        (NaiveDate::from_ymd(1971, 12, 1), &[][..])

Thank you !

**Comment by Enet4** [comment]
Hello @jmlaka, thank you very much for finding that! It appears to only be triggered in partial dates with year and month, so it was overlooked.

I would greatly appreciate a pull request with that test case and respective fix. Please let me know if you need any help.

**Comment by Enet4** [comment]
Resolved by #137
