### ISSUE TITLE
TOMO MG pixel data interpretation

### ISSUE THREAD

**Issue by bastien-solutions** [Enet4/dicom-rs#146]
Hello @Enet4,

After some tests, it seems that dicom-pixeldata is not able to build the ndarray for tomosynthesis.
Below is some information about one of the images used:

```
(0008,0005) SpecificCharacterSet                CS (1, 10 bytes): "ISO_IR 100"
(0008,0008) ImageType                           CS (9, 46 bytes): ["ORIGINAL", "PRIMARY", "TOMOSYNTHESIS", "NONE", ...
(0008,9205) PixelPresentation                   CS (1, 10 bytes): "MONOCHROME"
(0008,9206) VolumetricProperties                CS (1,  6 bytes): "VOLUME"
(0008,9207) VolumeBasedCalculationTechnique     CS (1, 14 bytes): "TOMOSYNTHESIS"
...
(7FE0,0010) PixelData                           OW (1,966951648 bytes)
```

I don't know if this is already identified.

**Comment by Enet4** [comment]
Thank you for reporting, @bastien-solutions. Any additional information that you might have of the issue may help confirm this: a small code example, the error value that is raised, and more meta-data attributes (at least _NumberOfFrames_, _Transfer Syntax UID_, _Bits Allocated_, _SamplesPerPixel_, and _PhotometricInterpretation_.

The _Pixel Representation_ attribute listed there is not compliant with the standard. It is expected to be either `0` (unsigned pixel values) or `1` (signed pixel values).

Other than that, at this point I can only I suspect that this has to do with being a multi-frame image in a native pixel data format.  Although the API for multi-frame images is yet to be defined (#123), the library should at least be able to retrieve a single frame at this point.

**Comment by bastien-solutions** [comment]
> Other than that, at this point I can only suspect that this has to do with being a multi-frame image in a native pixel data format. Although the API for multi-frame images is yet to be defined (#123), the library should at least be able to retrieve a single frame at this point.

You're perfectly right @Enet4 , my bad !
