### ISSUE TITLE
Cannot read transfer syntax UIDs with non-standard whitespace characters

### ISSUE THREAD

**Issue by Enet4** [Enet4/dicom-rs#148]
Currently, transfer syntax indices are required to be robust to the presence of a single null character at the end of a transfer syntax UID string, which is compliant with standard DICOM. But some DICOM implementations in the wild may put other whitespace characters at the end, which is not aligned with these expectations. While UID's are not supposed to have those whitespace, DICOM-rs could be a bit more resilient.

Originally mentioned in https://github.com/Enet4/dicom-rs/issues/50#issuecomment-889124095.

I am picturing two ways of making this work, not necessarily exclusive, but each would be sufficient:

### Approach 1: make the standard transfer syntax registry more flexible

Instead of just failing to find the transfer syntax, a more flexible implementation of [`TransferSyntaxRegistry::get`](https://github.com/Enet4/dicom-rs/blob/master/transfer-syntax-registry/src/lib.rs#L65) would:

- try to trim any kind of whitespace at the end of the string;
- and emit a warning if it finds a whitespace character other than `\0` (#49 is pending though; leave a TODO comment for now).

This is the least invasive approach and would work regardless of where the UID came from.

### Approach 2 (:warning: on hold for now): automatically trim the transfer syntax UID on file meta table building

Once the transfer syntax UID is found in the file meta group, trim any kind of whitespace before saving it, and emit a warning if it contained any non-standard DICOM whitespace (leave a TODO comment for #49).
This is probably what DCMTK does, according to https://github.com/Enet4/dicom-rs/issues/50#issuecomment-889186415, and stops the original mistake from propagating to subsequently written files, but it does not handle poor transfer syntax UID strings coming from elsewhere (such as an association request PDU), and it changes the current expectations of the file meta table, since it currently does no trimming of any value.

This issue would be resolved with either one, although I am probably more inclined towards doing approach 1. Whichever decision is made here is also going to influence #70.

**Comment by bastien-solutions** [comment]
I think the approach 2 is more dangerous since something other than a whitespace can follow a found UID (and this can be valid in case of a new UID).
I agree the approach 1 is more conservative and also more close to the behavior of existing libraries like DCMTK or DCM4CHE.
