### ISSUE TITLE
Association API implementation does not honor remote AE's maximum PDU length

### ISSUE THREAD

**Issue by Enet4** [Enet4/dicom-rs#163]
As identified in https://github.com/Enet4/dicom-rs/pull/158#discussion_r699315685, the association client is ignoring the connection acceptor's requested maximum PDU length, and as such may send PDUs which are too large for the destination to handle. This could also be happening at the server abstraction, but this is yet to be validated.

**Comment by charbeljc** [comment]
Hi @Enet4 I just added an option `--max-pdu-length` to `scpproxy` in #162 . With that in place, we have all needed parts to test en fix this issue, I guess.

**Comment by Enet4** [comment]
@charbeljc That I saw, it might indeed help! Testing will still likely to include an independent tool, so as to verify the PDU length calculations against it.

My plan will be to review and merge #162, then finish working on the pull request that should hopefully take care of this matter.
