### ISSUE TITLE
Add example code for dumping the tags that appear in the file.

### ISSUE THREAD

**Issue by mutantbob** [Enet4/dicom-rs#194]
I was able to figure out how to scan the list of elements in a dicom object using

```
    for x in obj {
        println!("{}", x.header().tag);
    }
```

But that gives me output like 

```
...
(0028,0102)
(0028,0103)
...
```

It would be helpful if the documentation included a code example that shows this scan including how to transform the tuples into string names usable in the `element_by_name()` method.  Not necessarily because this is optimal, but because it would be helpful for beginners to be able to inspect what fields appear in a DICOM file they are parsing.

**Comment by Enet4** [comment]
The upstream revision has a documented `dicom_dump` library, which will be released to crates.io soon.

```rust
use dicom::object::open_file;
use dicom_dump::dump_file;

let obj = open_file("path/to/file.dcm")?;
dump_file(&obj)?;
```
