### ISSUE TITLE
[storescu|echoscu] Compact way to set called AE title

### ISSUE THREAD

**Issue by Enet4** [Enet4/dicom-rs#204]
As a user of these tools, I would like to specify the called application entity title alongside the AE host and address, making it compact and easier to remember.

Instead of this:
```sh
dicom-storescu --called-ae-title PACS-ARCHIVE localhost:104
```

I would be able to write:

```sh
dicom-storescu PACS-ARCHIVE@localhost:104
```

**Comment by Almeida-a** [comment]
I believe this would require a change of the dicom-storescu syntax from:
```
dicom-storescu [FLAGS] [OPTIONS] <addr> [files]...
```
to:
```
dicom-storescu [FLAGS] [OPTIONS] <called-ae-title> | <addr> [files]...
```
And the equivalent for dicom echoscu (without the files tokens).
We would need also to keep backwards compatibility with older versions.
