### ISSUE TITLE
Using dicom_object::open_file

### ISSUE THREAD

**Issue by victorgabr** [Enet4/dicom-rs#21]
Hello, thank you for providing DICOM support for Rust.

I was trying to run a minimal example using this data.

[ftp://medical.nema.org/medical/dicom/DataSets/WG16/Siemens/Siemens_spectroEnhDICOM/](ftp://medical.nema.org/medical/dicom/DataSets/WG16/Siemens/Siemens_spectroEnhDICOM/)

```rust
use dicom_object::open_file;
use dicom_object::Result;

let file_path = "Anonymous.MR._.12.1.2017.06.28.09.41.02.294.59320505.dcm";
let obj = open_file(file_path);
let is_ok = obj.is_ok();
println!("is ok {}", is_ok);
```
Always print false. I tried with other datasets too.
My rustc version:

**rustc --version
rustc 1.38.0 (625451e37 2019-09-23)**

How can I make it work?

Thanks.

**Comment by Enet4** [comment]
Thank you for reporting. Please consider replacing that `is_ok()` with `unwrap()` or something that would allow us to see the error, and place that output here. If it is possible for you to provide that DICOM file, or one that reproduces the same problem, that would also be excellent. We happen to know that some files are currently unsupported (e.g. #20).

**Comment by victorgabr** [comment]
I wish I could help with this issue, but my background is C++ (DCMTK) and Python (Pydicom). But as an idea, you could design this crate to allow the user to be responsible for providing particular information on edge cases. For example, TransferSyntaxUID, etc. The DICOM standard is huge, with a lot of deprecated/new specifications. It is quite difficult to cover all cases.

**Comment by Enet4** [comment]
Thank you for the suggestion. It is true that some flexibility on how the application handles edge cases should be desired. I just found a few TODOs mentioning this too. Adding a set of options on whether the parser should be pedantic or relaxed would indeed be useful.

In this case though, it's pretty much a bug, and I would say having it return an error consistently was as ideal as we could ask for. :)

After some inspection of the code, I think I'll be able to fix this without expending too much time. Expect a pull request soon-ish.

**Comment by victorgabr** [comment]
Everything fine here!
I am planning to translate this 
 [https://github.com/victorgabr/ApertureComplexity](url) form Python to Rust.
 I guess it will keep me learning Rust.

It uses the element [BeamSequence](http://dicom.nema.org/medical/Dicom/2016a/output/chtml/part03/sect_C.8.8.14.html) and 

 [LeafJawPositions ](https://dicom.innolitics.com/ciods/rt-image/rt-image/30020030/300a00b6/300a011c) elements.

The crate dcmdump is being handy to check what is going on.

 Thanks for merging this.
