### ISSUE TITLE
Unexpected token ItemEnd

### ISSUE THREAD

**Issue by troelsarvin** [Enet4/dicom-rs#253]
Hello,

The attached DICOM test file makes dicom-rs' dicom-dump fail with error message "[ERROR] Unexpected token ItemEnd". dcm4che and dcmtk are both be able to dump its metadata.

Maybe something in parsing needs to be made more tolerant or robust?

[dummy.dcm.zip](https://github.com/Enet4/dicom-rs/files/8794355/dummy.dcm.zip)

**Comment by Enet4** [comment]
Thank you for reporting. It appears that the file contains an _ItemDelimitationItem_ at the end of the data set, even though it is unrelated to any sequence. Trimming the file at the end by 8 bytes would make it work normally.

I suppose a way to make it more robust is to deliberately skip item delimitation headers if it is known that we are not parsing an item at that position.

**Comment by troelsarvin** [comment]
I confirm that the change has made it possible for my code to parse the DICOM headers, thanks.

**Comment by troelsarvin** [comment]
I confirm that the change has made it possible for my code to parse the DICOM headers, thanks.

**Comment by Enet4** [comment]
Thank you for validating on your end. This issue will be closed automatically once #254 is resolved.
