### ISSUE TITLE
File meta information with zero length

### ISSUE THREAD

**Issue by ibaryshnikov** [Enet4/dicom-rs#27]
I have a case with `Tag(0x0002, 0x0001)`, `VR: OB`, and `Length(0)`. Is it a correct case? I haven't found a corresponding page in the standard so far.

**Comment by Enet4** [comment]
This is heavily related with #28. I have left a comment on this subject there. The way I see it, that is a non-compliant DICOM file.

**Comment by Enet4** [comment]
I will close this as a duplicate of #28. Nevertheless, new issues can be posted if additional cases of missing meta-data are found in the wild.
