### ISSUE TITLE
Handling Tag(0x0002, 0x0002) in FileMetaTable

### ISSUE THREAD

**Issue by ibaryshnikov** [Enet4/dicom-rs#28]
There's a number of different tags possible in file meta information, as described in http://dicom.nema.org/medical/dicom/current/output/chtml/part10/chapter_7.html#table_7.1-1
Is it possible to support additional tags in FileMetaTable, which at the moment has the following check
```rust
if elem.tag() != (0x0002, 0x0001) {
    return Err(Error::UnexpectedTag(elem.tag()));
}
```

**Comment by ibaryshnikov** [comment]
The file starts with
```rust
[
    b'D', b'I', b'C', b'M',
    // File Meta Information Group Length: (0000,0002) ; UL ; 4 ; 166
    0x02, 0x00, 0x00, 0x00, b'U', b'L', 0x04, 0x00, 0xa6, 0x00, 0x00, 0x00,
    // Media Storage SOP Class UID (0002, 0002) ; UI ; 26 ; ...
    0x02, 0x00, 0x02, 0x00, b'U', b'I', 0x1a, 0x00, 0x31, 0x2e, 0x32, 0x2e, 0x38, 0x34, 0x30,
    0x2e, 0x31, 0x30, 0x30, 0x30, 0x38, 0x2e, 0x35, 0x2e, 0x31, 0x2e, 0x34,
    0x2e, 0x31, 0x2e, 0x31, 0x2e,
]
```

**Comment by Enet4** [comment]
This appears to be another pseudo-DICOM file. The standard requires the File Meta Information Version attribute to be presented and have the length of 2 bytes, but perhaps the producer of that files just wants us to assume the values `00H, 01H`?

With that said, there is a known need to make the library more robust to DICOM _pseudo-ness_ such as this one. For one, programs should at least ignore meta fields which the library does not know about, and maybe provide reasonable defaults for missing ones. With this done, you would be able to fetch the following meta attributes as usual.

**Comment by ibaryshnikov** [comment]
Having reasonable defaults along with a warning that it's a non-compliant file sounds like a great idea
