### ISSUE TITLE
ul::client TcpStream hangs after .send()

### ISSUE THREAD

**Issue by jmlaka** [Enet4/dicom-rs#306]
Hello,
I've been playing with the findscu , sending requests to Orthanc but noticed, that C-Find fails.
Orthanc responds with: Find SCP Failed: DIMSE Failed to receive a message
This seems to happen when the ClientAssociation.send() sends the C-FIND dataset successfully and findscu calls the first 
.read() inside the loop,  `reader::read_pdu().`

Tweaking with some TcpStream properties didn't change anything.

I've been using the ServerAssociaton for my own C-FIND SCP for quite some time and never had problems with the reader.

Any thoughts on this please ?
Any guidance for diagnostics ?
Thanks

**Comment by Enet4** [comment]
Hello! I would start by collecting and providing details about how the CLI tool was used, then the query performed by the SCU, then the exact PDU that was sent to the SCP. A TCP packet capture tool could do this, but we can also infer this once the exact SCU data is known.

Admittedly, the current state of the find SCU is experimental. It was mostly tested on one PACS archive for the time being.

**Comment by jmlaka** [comment]
Found it, was just a typo .... see PR please

**Comment by Enet4** [comment]
Assuming fixed via #307
