### ISSUE TITLE
Typo error in description

### ISSUE THREAD

**Issue by arunjoshtech** [Enet4/dicom-rs#324]
Dear sir,
Please correct the spelling in the description
![Screenshot 2023-01-08 201257](https://user-images.githubusercontent.com/63642104/211202544-90ceba3d-e5f1-4d11-bbdf-78c0ea11ca0d.png)
 of protocol, Refer attached image for it

**Comment by Enet4** [comment]
Thank you for the heads up. That is fixed now.
