### ISSUE TITLE
Handling C-ECHO with storescp cli command

### ISSUE THREAD

**Issue by PierreBou91** [Enet4/dicom-rs#337]
Hello,

Thanks for this great project.

In an attempt to learn Rust and improve my understanding of the dicom standard, I am working on a very basic EAI (enterprise application integration). In doing so, I reused most of the storescp code from dicom-rs and I added the possibility to handle the C-ECHO request (It's enough to check the command value in the main loop and format a C-ECHO response).

Is it relevant to adapt my code to the storescp in this project and make a pull request or was this omission intentional ?

Have a nice day,

Pierre

**Comment by Enet4** [comment]
Hello! Thank you for your interest in DICOM-rs. I agree that there is value in `storescp` implementing the verification SOP class, so I would be happy to review your pull request!
