### ISSUE TITLE
Inspect shared/per-frame functional groups

### ISSUE THREAD

**Issue by Enet4** [Enet4/dicom-rs#349]
The decoding of pixel data via the trait [`PixelDecoder`](https://docs.rs/dicom-pixeldata/0.2.1/dicom_pixeldata/trait.PixelDecoder.html) is currently implemented for the default DICOM object type to retrieve basic Modality LUT function properties and VOI LUT properties at the root of the main data set, such as _Rescale Slope_, _Rescale Intercept_, _Window Width_, and _Window Center_. However, some classes of DICOM multi-frame data may encode this information in _functional groups_.

- The Modality LUT function (e.g. _Rescale Type_) may instead be specified in the _Pixel Value Transformation Sequence_ item of a functional group.
- And the VOI LUT function specification and properties (e.g. _VOI LUT Function_) may be present in a _Frame VOI LUT Sequence_ item.

In turn, these sequences may be either in the [_Shared Functional Groups Sequence_](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.html#table_C.7.6.16-1), when the properties are to be shared among multiple frames, or in a [_Per-frame Functional Groups Sequence_](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.html#table_C.7.6.16-1) item when these properties differ between frames.

While there may be many other scenarios than this, supporting the retrieval of Modality and VOI LUT function attributes in these functional groups would already serve as a great baseline. This in turn may require changing the specification of `DecodedPixelData` so that it may hold per-frame attributes, or retrieve them at a later date from the original object.

**Comment by naterichman** [comment]
Hi @Enet4 thank you for maintaining this wonderful package!  I have familiarity with dicom (particularly multi-frame), but am fairly new to rust.  Could you elaborate on what you'd like this ability to look like?  I'd like to take a crack at it if you are willing.

**Comment by Enet4** [comment]
Thank you for your interest @naterichman! I have expanded the issue with more information. I am also available for answering any questions and/or providing some guidance, if you are interested in going through with this feature.
