### ISSUE TITLE
dicom_dump not visible

### ISSUE THREAD

**Issue by jmlaka** [Enet4/dicom-rs#368]
The lib part of the dicom_dump is not visible when importing dicom-rs and so is not usable from external projects.

Can this be fixed by updating the `parent` crate ?

**Comment by Enet4** [comment]
> The lib part of the dicom_dump is not visible when importing dicom-rs and so is not usable from external projects.

It is still possible to import `dicom-dump` directly (this is the "pick what you need" way of using DICOM-rs). But as far as the parent crate is concerned, I agree that it would be useful if `dump` was available in `dicom` as well.
