### ISSUE TITLE
Error while trying to parse valid dicom file

### ISSUE THREAD

**Issue by vampolo** [Enet4/dicom-rs#37]
Hi,

I have this valid [dicom file](https://www.dropbox.com/s/wxlu9cj1repg58g/949559.dcm?dl=0). i tried to run the simple program in the readme but i receive the following error:

```
Error: ReadValue(ParseFloat(ParseFloatError { kind: Invalid }))
```

at the line

```
let obj = open_file("949559.dcm")?;
```

What can it be?

**Comment by Enet4** [comment]
Thank you for reporting. Would you like to try that again with the upstream version in the _master_ branch? I just opened that file using the project's `dcmdump` binary without errors.

**Comment by vampolo** [comment]
The one from master seems to work. Are you considering publishing an update?

**Comment by Enet4** [comment]
I'm afraid I don't have an estimated date for a new release yet. It depends on how many things I wish to include in the next version. Still, considering the growing interest in the project and the fair amount of goodies already pending a release, this will weigh in on the decision. Feel free to watch the repository for releases.

**Comment by Enet4** [comment]
Closing, as the original problem had already been fixed upstream. There are also plans for #12, which would "post-pone" value decoding errors to a later stage and prevent a single value from breaking the file reading process.

**Comment by Enet4** [comment]
Just letting you know that version 0.2.0 has just been released with the fixes described here.
