### ISSUE TITLE
detect_preamble and in extension from_reader_with_all_options doesn't check for size

### ISSUE THREAD

**Issue by DerOrfa** [Enet4/dicom-rs#404]
In detect_preamble in mem.rs

```rust
        if &buf[0..4] == b"DICM" {
            return Ok(ReadPreamble::Never);
        }
```
is done without checking if `buf` actually has at least 4 bytes, leading to panic when, for example, trying to read empty files with `from_reader_with_all_options` and friends.

Should return with io::Error.

**Comment by Enet4** [comment]
Thank you for reporting! Would you be able to send in a pull request?
