### ISSUE TITLE
Adding private data elements (with creator)

### ISSUE THREAD

**Issue by matthiasg** [Enet4/dicom-rs#431]
Is there any support in handling adding private elements ?

**Comment by Enet4** [comment]
At the moment, you can retrieve and insert elements with private tags, but they are treated like any other elements, and the private creator needs to be added or inspected manually.
The data element dictionary can also be replaced with a custom implementation, which would enable the recognition of private tags by their alias at run-time. With some work in this direction, the ecosystem could support a more streamlined experience when working with these.

**Comment by matthiasg** [comment]
Thanks for the quick feedback.

**Comment by naterichman** [comment]
@Enet4 I'm interested in picking this up. Mostly for looking up private tags with a group, creator, and element mask, i.e. 

If there was:
```
(0x0009, 0x0010)    LO     "MY CREATOR"
(0x0009, 0x1001)    SH     "My value"    
```
you could look it up like `dcm.private_element(0x0009, "MY CREATOR", 0x01)`.   And similarly something for adding a private element creating/reserving a block if necessary:

```rust
dcm.put_private_element(
    0x0009,
    "MY CREATOR",
    0x01,
    VR.SH, 
    Value::Primitive(
        PrimitiveValue::from("My Value".to_string())
    )
)
```

Just looking for your thoughts on design.  LMK!

**Comment by Enet4** [comment]
Thank you for the initiative, @naterichman! From what I know about private data elements, that API seems to go in the right direction, at least for the in-memory object implementation.

I've been thinking about how we would also incorporate this capability onto the Operations API (the attribute selectors only recognize tags and not private groups), and I would appreciate having more people thinking about this.

**Comment by naterichman** [comment]
@matthiasg Getting back to this if you have a chance to test this out with 0.7.0 and have feedback on the interface, let me know!
