### ISSUE TITLE
Storescp promiscuous mode

### ISSUE THREAD

**Issue by jennydaman** [Enet4/dicom-rs#477]
It is required to explicitly list all valid SOP class UIDs with `ServerAssociationOptions::with_abstract_syntax`. Would it be possible to support something similar to dcmtk storescp's "promiscuous" mode, so that unknown SOP classes are acceptable?

**Comment by Enet4** [comment]
Yes, it makes sense to support promiscuous mode. This might be best implemented at `dicom_ul::association::server`, where the presentation context negotiation logic resides.
`ServerAssociationOptions` would have a `promiscuous` flag field, and the method `establish` would be tweaked to accept any abstract syntax (I think).
