### ISSUE TITLE
First two bytes are not an SOI marker

### ISSUE THREAD

**Issue by IsmailAlamKhan** [Enet4/dicom-rs#537]
I am trying to open some US modality .dcm files but getting an error saying "JPEG decoding failure on frame 3", source: Some(Format("first two bytes are not an SOI marker"))". I was having this error on other .dcm files as well which was fixed on this #535  but only this study isn't opening. I have attached some .dcm files from that study.
[Archive.zip](https://github.com/user-attachments/files/16175893/Archive.zip)

**Comment by Enet4** [comment]
Thank you for bringing this up. After a more exhaustive check, it's true that some of the frames may still result in that error.

```sh
cargo run --bin dicom-toimage -- -F33 US000002.dcm
```
Runs fine, but

```sh
cargo run --bin dicom-toimage -- -F34 US000002.dcm
```

Results in

```none
2024-07-25T09:31:00.969153Z ERROR dicom_toimage: failed to decode pixel data

Caused by these errors (recent errors listed first):
  1: Could not decode pixel data
  2: JPEG decoder failure
  3: invalid JPEG format: first two bytes are not an SOI marker
```

**Comment by IsmailAlamKhan** [comment]
@Enet4 yep thats what happens. Thank you for checking it
