### ISSUE TITLE
open_file support for inferring MediaStorageSOPClassUID and MediaStorageSOPInstanceUID from SOP Class UID and SOP Instance UID

### ISSUE THREAD

**Issue by chrisbll971** [Enet4/dicom-rs#538]
Hello,

We have certain files that are missing MediaStorageSOPClassUID and MediaStorageSOPInstanceUID, however, they do have values for SOP Class UID and SOP Instance UID. Do you happen to know if there is a way to infer them from SOP Class UID and SOP Instance UID when using `open_file`?

If there isn't a way I'd be glad to send out a PR - open to suggestions on where the logic should go.

Thanks,
Chris

**Comment by Enet4** [comment]
Thank you for reporting! This seems heavily related to #255, and I agree that we could have a mechanism to infer those two attributes from the main data set. This subject has even been brought up on Zulip not long ago. https://dicom-rs.zulipchat.com/#narrow/stream/331273-general/topic/How.20to.20handle.20missing.20File.20Meta.20Group.20fields

Right now `dicom_object::mem` might be the best place to do this, in the various constructor functions.

**Comment by chrisbll971** [comment]
Awesome, I released a PR based on the discussion mentioned in the Zulip thread. #541
