### ISSUE TITLE
What about switching to encoding_rs?

### ISSUE THREAD

**Issue by alcir** [Enet4/dicom-rs#555]
https://github.com/Enet4/dicom-rs/blob/de7dc5831171202fb20e1928e2c7ff27c5b95f85/encoding/Cargo.toml#L16

Disclaimer: I'm not a developer.
encoding looks unmaintained (last commit 7 years ago). What about switching to encoding_rs instead?

**Comment by Enet4** [comment]
Seems like a duplicate of #200. That is practically in the project's plans. The migration isn't entirely trivial because the crates expose different APIs and some of the encodings are not directly available in `encoding_rs`.
