### ISSUE TITLE
Incorrect image when decoding multiframe pixeldata

### ISSUE THREAD

**Issue by thomas-tribus** [Enet4/dicom-rs#561]
I've noticed that pixeldata is decoded incorrectly when using `decode_pixel_data()` and then exporting individual frames. When exporting using `decode_pixel_data_frame` I get correct results. I'm using 2D ultrasound with `ybr_full_422` photometric interpretation.

So this works:

```rust
let frame = 0;
let pix = dicom.decode_pixel_data_frame(frame)?;
let img_data = pix.to_dynamic_image(0)?;
img_data.save("out.png")?;
```

And this doesn't:

```
let frame = 0;
let pixel_data = dicom.decode_pixel_data()?;
//The colors in the output are wrong
let img_data = pixel_data.to_dynamic_image(frame)?;
img_data.save("out.png")?;
```

Correct result:
![frame_0](https://github.com/user-attachments/assets/5b8fd534-2646-4676-9368-d924d9d20bd6)

Result when decoding all frames:
![frame_0](https://github.com/user-attachments/assets/919d79e6-b488-484f-bd32-0273a4e6b4c9)

I've found a likely culprit too, when using `decode_pixel_data` a new photometric interpretation is computed based on the number of channels in the input image (see below). The single frame `decode_pixel_data_frame` doesn't have this (seemingly incorrect) transformation.

```rust
// pixels are already interpreted,
// set new photometric interpretation
let new_pi = match samples_per_pixel {
    1 => PhotometricInterpretation::Monochrome2,
    3 => PhotometricInterpretation::Rgb,
    _ => photometric_interpretation,
};
```

I've created a PR that removes the code and that seems to fix the issue.

**Comment by thomas-tribus** [comment]
PR: https://github.com/Enet4/dicom-rs/pull/562

It seems I can't link it in the development panel, so here it is in the comments.

**Comment by Enet4** [comment]
Thank you for reporting. Seeing #562, this seems to be specific to the GDCM integration, correct? Is the ultrasound in JPEG baseline?
