### ISSUE TITLE
Usage of `inspect`  changed rust version of dicom-rs

### ISSUE THREAD

**Issue by qarmin** [Enet4/dicom-rs#585]
```
error[E0658]: use of unstable library feature 'result_option_inspect'
   --> /home/rafal/.cargo/git/checkouts/dicom-rs-165e2a1669724caa/ec178ec/parser/src/stateful/decode.rs:916:14
    |
916 |             .inspect(|_| {
    |              ^^^^^^^
    |
    = note: see issue #91345 <https://github.com/rust-lang/rust/issues/91345> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `dicom-parser` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

I use quite old rust 1.72.1, because this is the latest version supported by my yocto version.

Is the use of inspect(and perhaps other functions as well) currently worth increasing the minimum version of rust?

**Comment by Enet4** [comment]
Thank you for bringing this up. While there is currently no policy for Rust compiler compatibility other than "guaranteed to work on the latest stable", I also do not want small changes to be too disruptive and catch consumers off guard.

Rust 1.72.1 is one year old by now. The use of `inspect` on results and options can be reverted, but it would be good to know for how long things would have to stay compatible in that use case. Is the update to the Rust compiler blocked on the Yocto side?

**Comment by qarmin** [comment]
In Yocto hardknott which we use, openembedded-core does not support rust.
Layer meta-rust which we use supports at most 1.72.0, because newer versions require a newer cmake which is unavailable in version our Yocto version.

We have plans to move to a higher version of Yocto at the end of the year/early next year.

If possible, I suggest releasing version 0.8 with support for an older version of Rust, with plans to increase the Rust version in later releases.
