### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by ibaryshnikov** [Enet4/dicom-rs#6]
Is it a goal or non-goal?
It worked out of the box before 0.1, but not supported by inventory yet.

**Comment by Enet4** [comment]
Thank you for reporting. WebAssembly support is indeed planned, but it did not occur to me that the flexible transfer syntax registry would break compatibility.

If `inventory` really can't work in a wasm environment, we'll have to look for an alternate implementation.

**Comment by ibaryshnikov** [comment]
Thanks for a quick reply!

There's a related issue https://github.com/amethyst/amethyst/issues/1893, but `linkme` support for wasm is not ready yet https://github.com/dtolnay/linkme/issues/6

From the other side, it's possible to have mutable statics

```rust
lazy_static! {
    static ref REGISTRY: Mutex<TransferSyntaxRegistry> = {
        Mutex::new(TransferSyntaxRegistry { m: initialize_codecs() })
    };
}
```

the drawback is that it can affect performance.

One more option is to use decoder builder, keeping a local copy of transfer syntax registry per decoder

```rust
let decoder = DecoderBuilder::default()
    .with_transfer_syntax(extend it)
    .with_transfer_syntax(extend again)
    .build()?;
let object = decoder.from_reader(input)?;
```

What do you think? May be there is a better alternative which I missed.

**Comment by Enet4** [comment]
Considering that #17 has been merged, we can consider this resolved. We should strive to keep WebAssembly as a working target, although there is much to be done regarding testing. Please create a new issue if another problem emerges when using DICOM-rs in WebAssembly.
