### ISSUE TITLE
Colored dcmdump output

### ISSUE THREAD

**Issue by Enet4** [Enet4/dicom-rs#71]
It would be interesting to have the project's dcmdump print colored output for better readability and analysis.

This would give tag numbers, attribute names, and respective values, in different colours if the output device is a TTY.

[`termcolor`](https://crates.io/crates/termcolor) seems to be the right way to do this.

**Comment by pjsier** [comment]
@Enet4 I'm interested in taking this on! To clarify, in the example you mentioned there would be 3 colors assigned, one each for numbers, attribute names, and values? And do you have any preference on the colors used?

**Comment by Enet4** [comment]
Yes, the colours would differ among different components in a line.

To be honest, I did not specify concrete colours because this is likely going to be an iterative process for obtaining a good palette. Still, here's what I would picture as a good starting point for a dark background:

- a slightly darker shade of grey for the tag numbers;
- known attribute names in bold if supported by the platform
- values in a brighter colour, which could even depend on the data type and hint their validity: white or yellowish white for string values, light green for dates and times, red for invalid dates/times (this is already checked by dcmdump).

But again, we'll only know if they work well once tried out.

I will be able to test this on both Linux and Windows.

**Comment by pjsier** [comment]
Makes sense, thanks for clarifying! I can take an initial stab at some of the colors and then we can try them out to see what works

**Comment by pjsier** [comment]
@Enet4 I've been taking a look at `termcolor`, and it looks like the main benefit compared to something like [`colored`](https://github.com/mackwic/colored) is support for earlier versions of Windows. Is support for Windows versions before 10 a priority here? If so I can keep going forward with `termcolor`, but wanted to check because it looks like using `colored` is simpler overall

**Comment by Enet4** [comment]
That does seem to be an easier API. Feel free to use it for now. Then we can evaluate the outcomes based on platform support and performance.

**Comment by Enet4** [comment]
Resolved in #80
