### ISSUE TITLE
Add take_element methods for InMemoryDicomObject

### ISSUE THREAD

**Issue by Enet4** [Enet4/dicom-rs#78]
Allow the user of `dicom_object` to take the element from the object, removing it in the process.

For in-memory objects, this can translate to less data copying.

```rust
    /// <document please>
    pub fn take_element(&mut self, tag: Tag) -> Result<InMemElement<D>> {
        todo!()
    }

    /// <document please>
    pub fn take_element_by_name(&mut self, name: &str) -> Result<InMemElement<D>> {
        let tag = self.lookup_name(name)?;
        self.take_element(tag)
    }
```

**Comment by pjsier** [comment]
@Enet4 I'm interested in taking this on! To make sure I'm understanding, would it work to use the [`remove`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.remove) method of the `entries` `BTreeMap`?

**Comment by Enet4** [comment]
@pjsier Yes, I believe that would be it for the implementation. :+1: A quality PR would also include documentation and a basic test (alongside the ones in the same module).

**Comment by pjsier** [comment]
@Enet4 sounds great! I can work on that in the next few days
