### ISSUE TITLE
Using DCMTK for the standard dictionary

### ISSUE THREAD

**Issue by pauldotknopf** [Enet4/dicom-rs#8]
Take a look at [```dicom.dic```](https://github.com/DCMTK/dcmtk/blob/master/dcmdata/data/dicom.dic).

It is carefully curated by the DCMTK team, in coordination with the authors of the DICOM standard. It is also updated routinely with supplements (take a look at git history).

I recommend updating the dictionary build to use it, instead of the xml version of the DICOM standard. You wouldn't need the separate/static list of "META" entries. This change would also invalidate [this](https://github.com/Enet4/dicom-rs/pull/5) PR.

**Comment by Enet4** [comment]
I see. The dictionary builder could indeed be extended to support those files.

**Comment by pauldotknopf** [comment]
I am working on this now. What do you think about also publishing const static strings for each key? They way, we can avoid typos in implementations.

**Comment by Enet4** [comment]
> What do you think about also publishing const static strings for each key? 

Yes, this is also a good idea. We could have two kinds of Rust source code file outputs, one of them being a sequence of `pub const` declarations.
