### ISSUE TITLE
Using Dicom object 

### ISSUE THREAD

**Issue by moadmmh** [Enet4/dicom-rs#92]
Hello,
This may seem silly issue but i spent hours trying to figure out a way to solve this and i couldn't.
```
use dicom::core::*;
use dicom::object::*;

fn main() {
    let obj = open_file("01.dcm");
    let patient_name = obj.element_by_name("PatientName").to_str();
    let modality = obj.element_by_name("Modality").to_str();
    let pixel_data_bytes = obj.element(Tag(0x7FE0, 0x0010)).to_bytes();
}
```
I keep getting an error that `element_by_name` and `element` are not found.

**Comment by moadmmh** [comment]
I tried again to import it using 
`use dicom::object::DicomObject::element` and `use dicom::object::DicomObject::element_by_name`
but i got an error stating that `element` is not directly importable, cannot be imported directly rustc(E0253)

**Comment by moadmmh** [comment]
Fixed !

**Comment by Enet4** [comment]
Sorry, I only checked the issue tracker now. Glad you managed to figure it out anyway.

For future reference, most functions in the library return results, and so errors need to be handled in some way ([relevant section from the book](https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#recoverable-errors-with-result)).
